#!/usr/bin/env node
if (
  process.NativeModule &&
  process.NativeModule._cache &&
  process.NativeModule._cache.ELECTRON_ASAR
) {
  // won't log anything on good old fashioned node
  // only logs in electron
  process.stdout.write(process.NativeModule._cache.ELECTRON_ASAR.id)
} else {
  process.stdout.write(process.versions.modules)
}
